all:
	rm -f bin/parser
	rm -f bin/parser
	cp src/parser.py bin/
	cp src/grammar.py bin/
	cp src/lexer.py bin/
	cp src/output_format.py bin/
	chmod u+x bin/parser.py
	mv bin/parser.py bin/parser
	
clean:
	rm -f bin/*.py
	rm -f bin/parser
	rm -f bin/*.pyc
	rm -f bin/parser.out
