
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightGETSleftORleftANDrightNOTnonassocLTEQGTEQLTGTEQUALleftPLUSMINUSleftTIMESDIVIDEMODrightISVOIDrightTILDAleftATleftPERIODIMPORT CLASS INHERITS PUBLIC PRIVATE SEMICOLON COLON ID LSQRBRACKET RSQRBRACKET LPAREN RPAREN LBRACE RBRACE PERIOD OBJECT CLASS_TYPE INTEGER INTEGER_TYPE BOOL_TYPE STRING_TYPE SELF_TYPE STRING TRUE FALSE MOD TILDA GT LT EQUAL LTEQ GTEQ GETS OR AND NOT IF THEN ELSE FI WHILE LOOP POOL FOR LET IN SELF BREAK CONTINUE ISVOID NEW PLUS MINUS TIMES DIVIDE COMMA ATprogram : classesclasses : class SEMICOLONclass : CLASS CLASS_TYPE INHERITS CLASS_TYPE LBRACE features_list RBRACEfeatures_list : feature SEMICOLONfeature : ID LPAREN RPAREN COLON type LBRACE expression RBRACEtype : SELF_TYPEexpression : ID LPAREN argument_list RPARENargument_list : expressionexpression : STRING'
    
_lr_action_items = {'INHERITS':([5,],[7,]),'LBRACE':([8,18,19,],[9,-6,20,]),'RPAREN':([15,23,26,27,28,],[16,-9,28,-8,-7,]),'CLASS_TYPE':([2,7,],[5,8,]),'SEMICOLON':([4,11,13,24,],[6,14,-3,-5,]),'RBRACE':([10,14,21,23,28,],[13,-4,24,-9,-7,]),'ID':([9,20,25,],[12,22,22,]),'COLON':([16,],[17,]),'LPAREN':([12,22,],[15,25,]),'SELF_TYPE':([17,],[18,]),'STRING':([20,25,],[23,23,]),'CLASS':([0,],[2,]),'$end':([1,3,6,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expression':([20,25,],[21,27,]),'feature':([9,],[11,]),'features_list':([9,],[10,]),'classes':([0,],[3,]),'argument_list':([25,],[26,]),'type':([17,],[19,]),'class':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> classes','program',1,'p_program','mini_parser.py',25),
  ('classes -> class SEMICOLON','classes',2,'p_classes','mini_parser.py',29),
  ('class -> CLASS CLASS_TYPE INHERITS CLASS_TYPE LBRACE features_list RBRACE','class',7,'p_class_with_inheritance_with_features_list','mini_parser.py',38),
  ('features_list -> feature SEMICOLON','features_list',2,'p_features_list','mini_parser.py',42),
  ('feature -> ID LPAREN RPAREN COLON type LBRACE expression RBRACE','feature',8,'p_feature','mini_parser.py',46),
  ('type -> SELF_TYPE','type',1,'p_type_self_type','mini_parser.py',51),
  ('expression -> ID LPAREN argument_list RPAREN','expression',4,'p_expression_function_call_with_arguments_2','mini_parser.py',55),
  ('argument_list -> expression','argument_list',1,'p_argument_list','mini_parser.py',59),
  ('expression -> STRING','expression',1,'p_expression_string','mini_parser.py',64),
]
